### ISSUE TITLE
ユーザー管理機能

### ISSUE THREAD

**Issue by ks022564** [ks022564/consumables-checker#3]
# 実装内容の説明
・Deviseの導入を行う。新規登録/ログイン/ログアウトができるまで実装する。モデルのテストコードを行う。
# TASK
- [x] モデルにてバリデーションの記述を行うこと。
- [x] 必要な情報を適切に入力して「会員登録」ボタンを押すと、ユーザーの新規登録ができること。
- [x] 必要な情報を適切に入力して「ログイン」ボタンを押すと、ユーザーのログインができること。
- [x] 新規登録・ログイン共にエラーハンドリングができること（入力に問題がある状態で「会員登録」または「ログイン」ボタンが押された場合、情報は受け入れられず、各ページでエラーメッセージが表示されること）。
- [x] エラーハンドリングによって新規登録/ログインページに戻った場合でも、入力済みの項目（パスワード・パスワード確認用以外）は消えないこと。
- [x] テストコードを実行する
