### ISSUE TITLE
消耗品詳細表示機能

### ISSUE THREAD

**Issue by ks022564** [ks022564/consumables-checker#6]
# 実装内容の説明
・消耗品詳細表示ページにて、消耗品の詳細情報を表示する。
# TASK
- [ ] 消耗品一覧画面にて「詳細」ボタンをクリックすると、該当の消耗品の詳細画面へ遷移する。
- [ ] 消耗品登録時に登録した（設備名・型番・シリアルナンバー・消耗品名・消耗品型番・メーカー・交換周期・使用開始日）が表示されること。
- [ ] 点検作業日・次回点検予定日・実施者・コメントを入力して、保存ができること
- [ ] 「編集」ボタンで編集ページへ遷移できること
- [ ] 「削除」ボタンで削除できること
